### ISSUE TITLE
Remove OMP num thread from launcher scripts

### ISSUE THREAD

**Issue by bjoo** [weinbe2/summit-runscript#1]
Hi Evan, 
  I would remove the OMP_NUM_THREADS from the launcher script, as that way you can use launchers with either 1 thread (e.g. QDP-JIT) or with multiple threads (e.g. non-JIT hybrid OpenMP-MPI jobs)
I would leave that to the calling script...

Best, B

**Comment by weinbe2** [comment]
Done!
